### PR TITLE
Update Ember CLI and remove legacy tests

### PR DESCRIPTION
**Pull request by sir-dunxalot**
This PR updates Ember CLI to the latest release.

### CODE REVIEW

**Comment by lolmaus** [comment]
@sir-dunxalot Nice work! I'm using it in my app now.

Please release this. Instead of keeping the addon forever broken for modern Ember CLI, release this fix and open an issue for better test coverage.

**Comment by ryanto** [comment]
👍 Have been using this in production for the last few days, no issues so far. Great work!

**Comment by sir-dunxalot** [comment]
Released as `0.2.1`.

**Comment by lolmaus** [comment]
:bow:

**Pull request merged**
