### PR TITLE
disqus_url support, fixes #7, #8, #12

### LINKED ISSUE #7: Overriding init without calling this._super is deprecated
Installing this results in the following deprecation message:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/var/www/myproject/node_modules/ember-cli/lib/models/addon.js:1009:27)
```

```
Ember      : 2.7.0
Ember Data : 2.7.0
jQuery     : 2.2.4
```

### LINKED ISSUE #8: Add support to fetch thread by url
When you have multiple sites, you can share a thread with other sites if they are whitelisted in the admin panel.

In order to do this, you need to specify `disqus_url` and omit `identifier`.

### PR DESCRIPTION
**Pull request by Redsandro**
Hi @sir-dunxalot, this adds support to share threads across whitelisted sites.
It also gets rid of that deprecation message from using an old version of `ember-cli-htmlbars`.

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Sorry @Redsandro I completely missed this PR. I will make any comments now. I also restarted the build because the tests seemed to fail out before they ran.

**Comment by sir-dunxalot** [comment]
I have no code comments but it would be great if you could make sure the tests still pass before we merge this.

**Comment by Redsandro** [comment]
@sir-dunxalot How can I manually run tests locally?

I don't trust this travis-ci, running infinitely and then failing.

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

With the minor changes, with some of the tests I'm thinking the tests were already failing. Because Ember 2.7.0 is a lot newer than the last master commit.

There is no assert message. Just that the test couldn't be loaded
https://travis-ci.org/sir-dunxalot/ember-disqus/jobs/149192374

Can you restart the build on master to see if it checks out?

**Comment by sir-dunxalot** [comment]
It looks like master is failing with the same issues so I will merge this soon, pull down and fix the tests locally. If you wanted to do that locally in the meantime, tests run like any regular Ember addon (either `ember test` in the CLI or visit the `/tests` route in the dummy app after running `ember s`).

I'll try to merge this within the next couple of days but it might end up happening next week.

**Comment by lolmaus** [comment]
@Redsandro I've filed a PR to bump `ember-cli-htmlbars` again so that the addon stays compatible with Ember CLI 2.11. When you merge it, you can include #12 into this PR's title.

**Comment by lolmaus** [comment]
@Redsandro Oh, and please protect your `disqusUrlPatch` branch on GitHub against accidental deletion. I'm depending on it.

**Comment by Redsandro** [comment]
@lolmaus nice of you. Merged. Builds still failing though, but it's not because of this PR.

**Comment by Redsandro** [comment]
@sir-dunxalot I've merged your latest master and 4 out of 6 builds run successfully. The two that failed didn't fail with a clear reason; they timed out.

Would you take another look at this? Every time I accidentally update `ember-disqus` I have to change the `package.json` version:

```
"ember-disqus": "github:Redsandro/ember-disqus#cf97f14276a9bad8786e45b01c27c7e12132c436",
``` 

I've upgraded from Ember 2.7 all the way to Ember 3.3 so I'm "pretty sure" it works.

**Comment by sir-dunxalot** [comment]
Yes - will take a look at this now. Maybe something as simple as updating the Ember CLI dev environment will enable to tests to pass. Or perhaps it's related to Travis config. Either way, I will report back.

**Comment by sir-dunxalot** [comment]
Since this build is passing for current Ember versions, I'm going to merge and work on this on master.

**Comment by Redsandro** [comment]
Thanks @sir-dunxalot!

:coffee: :coffee: :coffee: 

Here are some coffee emoji's encouraging you to push a version to npm before Ember 3.4 comes out. :sunglasses:

**Comment by sir-dunxalot** [comment]
Thanks for the support @Redsandro! You will be pleased to hear that I have finished updating the dev environment, including test suite and everything is passing (was a bit more complicated that expected).

The support for this PR is #15, which is now merged into master and will be released.

Thanks again for the work!

**Comment by sir-dunxalot** [comment]
Released as 1.0.0.

**Pull request merged**
